import test from "node:test";
import assert from "node:assert/strict";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fixture, git } from "./fixture.mjs";
import {
  materialize,
  records,
  presetFor,
  supportedPreset,
  PRESET,
  recordHash,
} from "../dist/build.js";
import { normalizeFilePolicy, fileDecision } from "../dist/file-policy.js";
import { hash } from "../dist/common.js";
import { ManagedStore } from "./managed-store.mjs";
import { publish } from "../dist/publish.js";

test("file rules are validated, ordered, repo-relative and part of the pinned preset", () => {
  const policy = normalizeFilePolicy({
    version: 1,
    rules: [
      { pattern: "**", action: "exclude" },
      { pattern: "src/**", action: "semantic" },
      { pattern: "**/*.csv", action: "lexical" },
    ],
  });
  for (const [path, action] of [
    ["README.md", "exclude"],
    ["src/a.ts", "semantic"],
    ["src/nested/b.ts", "semantic"],
    ["src/line\nbreak.ts", "semantic"],
    ["data.csv", "lexical"],
    ["src/data.csv", "lexical"],
  ])
    assert.equal(fileDecision(path, policy).action, action, path);
  assert.equal(
    fileDecision("src/a.ts", {
      version: 1,
      rules: [{ pattern: "src/*.ts", action: "lexical" }],
    }).action,
    "lexical",
  );
  assert.equal(
    fileDecision("src/deep/a.ts", {
      version: 1,
      rules: [{ pattern: "src/*.ts", action: "lexical" }],
    }).action,
    "semantic",
  );
  for (const value of [
    null,
    {},
    { version: 2, rules: [] },
    { version: 1, rules: [], extra: 1 },
    ...[
      "/src/**",
      "../src/**",
      "a/**b",
      "!eval/**",
      "src/[ab]",
      "",
      "a//b",
      "a\\b",
    ].map((pattern) => ({
      version: 1,
      rules: [{ pattern, action: "exclude" }],
    })),
    { version: 1, rules: [{ pattern: "**", action: "oops" }] },
  ]) {
    assert.throws(() => normalizeFilePolicy(value));
    assert.equal(supportedPreset({ ...PRESET, filePolicy: value }), false);
  }
  for (const model of [
    "none",
    "text-embedding-3-small",
    "text-embedding-3-large",
  ]) {
    const preset = presetFor(model, ["standard"], policy);
    assert.ok(supportedPreset(preset));
    assert.notEqual(hash(preset), hash(presetFor(model)));
    assert.notEqual(
      hash(preset),
      hash(
        presetFor(model, ["standard"], {
          ...policy,
          rules: [...policy.rules].reverse(),
        }),
      ),
    );
  }
});

test("default policy excludes bodies, keeps lexical-only source and preserves meaningful code/prose", async (t) => {
  const f = await fixture();
  t.after(f.cleanup);
  const excluded = {
    ".env": "credential-file",
    "config/.env.production": "credential-file",
    ".npmrc": "credential-file",
    "certs/fake.PEM": "crypto-material",
    "certs/fake.key": "crypto-material",
    "secrets.txt": "private-key-content",
    ".venv/lib/dependency.py": "dependency-or-build-output",
    "third_party/library.c": "dependency-or-build-output",
    ".cache/output.txt": "dependency-or-build-output",
    "bundle.min.JS": "generated-output",
    "logs/build.log": "log-output",
  };
  const lexical = {
    "package-lock.json": "lockfile",
    "Cargo.lock": "lockfile",
    "go.sum": "lockfile",
    LICENSE: "legal-or-attribution",
    "docs/AUTHORS.rst": "legal-or-attribution",
    "generated/client.pb.go": "generated-source",
    "client.py": "generated-source",
    "tests/__snapshots__/widget.txt": "data-or-snapshot",
    "samples/data.csv": "data-or-snapshot",
  };
  const sources = {
    "client.py":
      "# Code generated by fixture. DO NOT EDIT.\ndef fixture():\n    return 1\n",
    "generated/client.pb.go":
      "package fixture\nfunc Value() int { return 1 }\n",
    "secrets.txt":
      "-----BEGIN PRIVATE KEY-----\nSYNTHETIC_NOT_A_REAL_KEY\n-----END PRIVATE KEY-----\n",
    "src/useful.ts": "export function useful() { return 42; }\n",
    "tests/test_useful.py": "def test_useful():\n    assert 42 == 42\n",
    "docs/conf.py":
      "# autogenerated file.\n# Customize configuration here.\nproject = 'Fixture'\n",
    "README.md": "# How it works\nUseful explanation.\n",
    "package.json": '{"name":"fixture","scripts":{"test":"node --test"}}\n',
    "config.yaml": "retry: 3\n",
    ".env.example": "EXAMPLE_TOKEN=PLACEHOLDER\n",
    "certs/README.md":
      "# Certificate fixtures\nThese files test TLS behavior.\n",
    "eval/answers.json": '{"answer":"test-only-answer"}\n',
  };
  for (const path of [
    ...Object.keys(excluded),
    ...Object.keys(lexical),
    ...Object.keys(sources),
  ]) {
    await mkdir(dirname(join(f.path, path)), { recursive: true });
    await writeFile(
      join(f.path, path),
      sources[path] ?? "SYNTHETIC_NOT_A_REAL_SECRET\n",
    );
  }
  git(f.path, "add", "-f", ".");
  git(f.path, "commit", "-qm", "synthetic policy fixtures");
  const ref = git(f.path, "rev-parse", "HEAD");
  const build = async (name, preset, previous) =>
    materialize({
      identity: f.source,
      ref,
      output: join(f.root, name),
      preset,
      previous,
    });
  const preset = presetFor("text-embedding-3-small");
  const baseline = await build("policy-default", preset);
  const docs = [];
  for await (const doc of records(baseline.directory)) docs.push(doc);
  for (const [path, reason] of Object.entries(excluded)) {
    assert.equal(
      baseline.inventory.find((e) => e.path === path).reason,
      reason,
      path,
    );
    assert.ok(!docs.some((d) => d.path === path), path);
  }
  for (const [path, reason] of Object.entries(lexical)) {
    assert.ok(
      docs.some((d) => d.path === path && d.kind === "file"),
      path,
    );
    const chunks = docs.filter((d) => d.path === path && d.kind === "chunk");
    assert.ok(chunks.length, path);
    for (const d of chunks) {
      assert.equal(d.embeddingStatus, "skipped", path);
      assert.equal(d.embeddingSkipReason, reason, path);
      assert.equal(d.embeddingText, undefined, path);
      assert.equal(d.embedding, undefined, path);
      assert.equal(recordHash(d, preset), hash(d));
      assert.throws(
        () => recordHash({ ...d, embedding: [1] }, preset),
        /Unexpected managed/,
      );
    }
  }
  for (const path of [
    "src/useful.ts",
    "tests/test_useful.py",
    "README.md",
    "package.json",
    "config.yaml",
    ".env.example",
    "certs/README.md",
    "docs/conf.py",
  ])
    assert.ok(
      docs.some((d) => d.path === path && d.embeddingStatus === "managed"),
      path,
    );

  const configured = presetFor("text-embedding-3-small", undefined, {
    version: 1,
    rules: [
      { pattern: "eval/**", action: "exclude" },
      { pattern: "third_party/**", action: "lexical" },
      { pattern: "generated/**", action: "semantic" },
      { pattern: ".env", action: "semantic" },
      { pattern: "secrets.txt", action: "semantic" },
      { pattern: "certs/**", action: "semantic" },
      { pattern: "*.svg", action: "semantic" },
    ],
  });
  const custom = await build("policy-custom", configured);
  const customDocs = [];
  for await (const doc of records(custom.directory)) customDocs.push(doc);
  for (const path of [
    "eval/answers.json",
    ".env",
    "secrets.txt",
    "certs/fake.PEM",
    "certs/fake.key",
    "logo.svg",
  ])
    assert.ok(!customDocs.some((d) => d.path === path), path);
  assert.ok(
    customDocs.some(
      (d) => d.path === "third_party/library.c" && d.kind === "file",
    ),
  );
  assert.ok(
    customDocs.some(
      (d) =>
        d.path === "generated/client.pb.go" && d.embeddingStatus === "managed",
    ),
  );
  await assert.rejects(
    build("bad-baseline", configured, baseline),
    /config mismatch/,
  );
  const reused = await build("reuse", configured, custom);
  assert.equal(reused.recordsHash, custom.recordsHash);
  assert.equal(reused.inventoryHash, custom.inventoryHash);

  // Publishing must not require or synthesize vectors on lexical-only files.
  const store = new ManagedStore(1536);
  await publish({
    store,
    binding: {
      repoId: "fixture",
      indexId: "fixture",
      repoKey: f.source.key,
      configHash: custom.configHash,
    },
    build: custom,
    state: join(f.root, "publish-state"),
    pollMs: 1,
  });
});
